### ISSUE TITLE
About srgb-to-linear.cube

### ISSUE THREAD

**Issue by RayChanNya** [dantmnf/qdcm-diy#1]
I tried to use this tools without "args.lut3d" and "args.output_shaper" because the process to generate them requires to files named "srgb-to-linear.cube" and "linear-to-srgb.cube" , and that results an error under:

`
found igc feature
found gc feature
Traceback (most recent call last):
  File "D:\meow\qdcm-diy\qdcm-diy", line 8, in <module>
    main()
  File "D:\meow\qdcm-diy\qdcmdiy\__main__.py", line 68, in main
    patch(args.filename, args.mode, args.input_shaper, args.lut3d, args.output_shaper)
  File "D:\meow\qdcm-diy\qdcmdiy\__main__.py", line 24, in patch
    mode.set_color_pipeline(pipeline)
  File "D:\meow\qdcm-diy\qdcmdiy\store_xml.py", line 101, in set_color_pipeline
    set_inner_text(gc_feature, lut3x1d_to_igc_xml(pipeline.gamma))
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\meow\qdcm-diy\qdcmdiy\store_xml.py", line 9, in lut3x1d_to_igc_xml
    if lut.size != 256:
       ^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'size'
`

And after I checked the code I found that code in store_xml.py line 101 used this:

`
                set_inner_text(gc_feature, lut3x1d_to_igc_xml(pipeline.gamma))
`

That might be an error or sth? By the way the newer version of colour-science can't work.

**Comment by dantmnf** [comment]
Thank you for raising this, the two files have been uploaded.

**Comment by RayChanNya** [comment]
看了一下主页，似乎可以用中文，那顺便提一下（
我觉得你应该看一眼store_xml.py的101行，检查了.degamma存不存在，结果用的是gamma的pipeline，是不是顺手写错了之类的（
以及新的色彩科学库不工作的原因似乎是你检查了导入的lut是不是3x1d lut，但是新版色彩科学库返回的类型改变了，把这个检查删掉新版色彩科学库也能正常工作了
不过需要下载的依赖从colour-science变成了colour-science[optional]，不然有一个库会不可用的样子

**Comment by dantmnf** [comment]
> 检查了.degamma存不存在，结果用的是gamma的pipeline，是不是顺手写错了之类的（

确实，从上面复制下来忘改了（

> 但是新版色彩科学库返回的类型改变了

看起来并没有，至少它工作在我的机器（

> 不然有一个库会不可用的样子

看起来是 matplotlib，本来就没用到，问题不大

**Comment by RayChanNya** [comment]
喵呜，没有问题了，谢谢喵（
